# Generated by Django 4.2.7 on 2026-03-22 08:45

import apps.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=15)),
                ('cv_file', models.FileField(help_text='Uploaded CV file (PDF/DOCX)', upload_to=apps.candidates.models.candidate_file_path)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from CV')),
                ('skills', models.JSONField(default=list, help_text='Extracted skills as JSON array')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True)),
                ('education', models.TextField(blank=True, help_text='Education information')),
                ('embedding_vector', models.JSONField(default=list, help_text='OpenAI embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether candidate profile is active')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
