# Generated by Django 4.2.7 on 2026-03-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_profile_json',
            field=models.JSONField(blank=True, default=dict, help_text='Structured CV profile from OpenAI JSON extraction'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Full name', max_length=200),
        ),
    ]
