# Generated by Django 4.2.7 on 2026-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_openai_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="ai_profile_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured CV profile from LLM (OpenAI/Gemini) file extraction",
            ),
        ),
    ]
