# Generated by Django 4.2.7 on 2026-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_openai_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fairness_scan_json',
            field=models.JSONField(blank=True, default=dict, help_text='Gender/age proxy detection and notes for HR review (transparency only)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_summary',
            field=models.TextField(blank=True, default='', help_text='Short professional summary from CV extraction (LLM)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ai_profile_json',
            field=models.JSONField(blank=True, default=dict, help_text='Structured CV profile from LLM (OpenAI/Gemini) file extraction'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=32),
        ),
    ]
