# Generated by Django 4.2.7 on 2026-03-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_alter_candidate_ai_profile_json"),
        ("candidates", "0004_compliance_explainability"),
    ]

    operations = []
