# Generated by Django 4.2.7 on 2026-03-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('candidates', '0005_merge_20260322_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='target_job',
            field=models.ForeignKey(blank=True, help_text='Nomzod ariza qilgan asosiy vakansiya (CV upload job_id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_candidates', to='jobs.job'),
        ),
    ]
