# Generated by Django 4.2.7 on 2026-03-26 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0006_candidate_target_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL', max_length=300),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked candidate user account (role=candidate)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
