# Generated by Django 4.2.7 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', help_text='Type of employment', max_length=20)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], default='mid', help_text='Job level/seniority', max_length=20)),
                ('required_skills', models.JSONField(default=list, help_text='Required skills as JSON array')),
                ('preferred_skills', models.JSONField(default=list, help_text='Preferred skills as JSON array')),
                ('min_experience', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required')),
                ('max_experience', models.PositiveIntegerField(blank=True, help_text='Maximum years of experience', null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Salary currency', max_length=3)),
                ('embedding_vector', models.JSONField(default=list, help_text='OpenAI embedding vector for job description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether job posting is active')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
