# Generated by Django 4.2.7 on 2026-03-26 09:59

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL (for candidates)', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to=apps.users.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Company name (for recruiters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='recruiter', help_text='User role: recruiter or candidate', max_length=20),
        ),
    ]
