# Generated by Django 4.2.7 on 2026-03-22 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField(help_text='AI-generated matching score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ai_rank', models.PositiveIntegerField(help_text='AI-generated rank position')),
                ('matched_skills', models.JSONField(default=list, help_text='Skills that matched between candidate and job')),
                ('missing_skills', models.JSONField(default=list, help_text='Skills required by job but missing in candidate')),
                ('explanation', models.TextField(help_text='Human-readable explanation of the ranking decision')),
                ('bias_flags', models.JSONField(default=list, help_text='Potential bias indicators detected')),
                ('human_decision', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted')], default='pending', help_text='Human recruiter decision', max_length=20)),
                ('human_score', models.FloatField(blank=True, help_text='Human-assigned score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('human_feedback', models.TextField(blank=True, help_text='Human feedback on the AI recommendation')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When human review was conducted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_rankings',
                'ordering': ['ai_rank'],
            },
        ),
        migrations.CreateModel(
            name='RankingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_openai_embeddings', models.BooleanField(default=True, help_text='Whether OpenAI embeddings were used')),
                ('candidates_count', models.PositiveIntegerField(default=0, help_text='Number of candidates ranked in this session')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the ranking session')),
            ],
            options={
                'db_table': 'ranking_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
