# Generated by Django 4.2.7 on 2026-03-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('ranking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ranking_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingsession',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_sessions', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rankings', to='ranking.rankingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateranking',
            unique_together={('session', 'candidate')},
        ),
    ]
