# Generated by Django 4.2.7 on 2026-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateranking',
            name='match_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Structured job–candidate match dimensions and narratives'),
        ),
    ]
