# Generated by Django 4.2.7 on 2026-03-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_compliance_explainability'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateranking',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether a decision email has been sent to the candidate'),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the decision email was sent', null=True),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='email_type',
            field=models.CharField(blank=True, help_text='Type of last email sent: accept | reject', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateranking',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List of specific rejection reasons with scores and explanations'),
        ),
    ]
