# Generated by Django 4.2.7 on 2026-03-26 17:13

import django.core.validators
from django.db import migrations, models


def backfill_rank_float(apps, schema_editor):
    CandidateRanking = apps.get_model("ranking", "CandidateRanking")
    for cr in CandidateRanking.objects.filter(rank__isnull=True).iterator(chunk_size=500):
        if cr.ai_rank is not None:
            cr.rank = float(cr.ai_rank)
            cr.save(update_fields=["rank"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_candidateranking_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateranking',
            name='rank',
            field=models.FloatField(blank=True, help_text='Final rank stored as float (typically float(ai_rank), 1-based). Saved to DB for API and audit.', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RunPython(backfill_rank_float, noop_reverse),
    ]
