# Generated by Django 4.2.7 on 2026-03-26 17:18

import django.core.validators
from django.db import migrations, models


def rank_score_0_100(position: int, session_total: int) -> float:
    n = int(session_total)
    pos = int(position)
    if n <= 0:
        return 0.0
    pos = max(1, min(pos, n))
    return round(100.0 * (n - pos + 1) / n, 4)


def backfill_rank_0_100(apps, schema_editor):
    CR = apps.get_model("ranking", "CandidateRanking")
    for cr in CR.objects.select_related("session").iterator(chunk_size=300):
        n = int(cr.session.candidates_count or 0)
        pos = int(cr.ai_rank or 0)
        if n > 0 and pos > 0:
            cr.rank = rank_score_0_100(pos, n)
            cr.save(update_fields=["rank"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_candidateranking_rank_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateranking',
            name='rank',
            field=models.FloatField(blank=True, help_text='Leaderboard rank on 0–100 scale from session position (best ≈ 100).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.RunPython(backfill_rank_0_100, noop_reverse),
    ]
