# Generated by Django 4.2.7 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('openai_model', models.CharField(default='text-embedding-3-small', help_text='OpenAI embedding model to use', max_length=50)),
                ('embedding_dimensions', models.PositiveIntegerField(default=1536, help_text='Embedding vector dimensions')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Minimum similarity threshold for matching')),
                ('bias_detection_enabled', models.BooleanField(default=True, help_text='Enable bias detection in rankings')),
                ('bias_keywords', models.JSONField(default=list, help_text='Keywords that might indicate bias')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('embedding_generation', 'Embedding Generation'), ('ranking_accuracy', 'Ranking Accuracy'), ('bias_detection', 'Bias Detection'), ('human_feedback', 'Human Feedback')], help_text='Type of metric being recorded', max_length=30)),
                ('metric_name', models.CharField(help_text='Specific metric name', max_length=100)),
                ('metric_value', models.FloatField(help_text='Numeric value of the metric')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the metric')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_session_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(help_text='SHA-256 hash of the content', max_length=64, unique=True)),
                ('content_type', models.CharField(choices=[('cv_text', 'CV Text'), ('job_description', 'Job Description')], help_text='Type of content that was embedded', max_length=20)),
                ('embedding_vector', models.JSONField(help_text='The cached embedding vector')),
                ('model_used', models.CharField(help_text='OpenAI model used for embedding', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=1, help_text='Number of times this embedding has been reused')),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'embedding_cache',
                'ordering': ['-created_at'],
            },
        ),
    ]
