# Generated by Django 4.2.7 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('ranking', 'AI Ranking'), ('override', 'Human Override'), ('review', 'Human Review'), ('export', 'Data Export'), ('login', 'User Login'), ('logout', 'User Logout'), ('ai_prediction', 'AI Prediction'), ('bias_check', 'Bias Check')], help_text='Type of action performed', max_length=20)),
                ('action_description', models.CharField(help_text='Detailed description of the action', max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', help_text='Risk level of this action', max_length=10)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context and data about the action')),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence score if applicable', null=True)),
                ('ai_explanation', models.TextField(blank=True, help_text='AI explanation or reasoning if applicable')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('audit', 'Audit Report'), ('incident', 'Incident Report')], help_text='Type of compliance report', max_length=20)),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('report_data', models.JSONField(help_text='Structured report data')),
                ('summary', models.TextField(help_text='Executive summary of the report')),
                ('period_start', models.DateTimeField(help_text='Start date of the reporting period')),
                ('period_end', models.DateTimeField(help_text='End date of the reporting period')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('high_risk_actions_count', models.PositiveIntegerField(default=0, help_text='Number of high-risk actions in this period')),
                ('bias_incidents_count', models.PositiveIntegerField(default=0, help_text='Number of potential bias incidents detected')),
                ('human_overrides_count', models.PositiveIntegerField(default=0, help_text='Number of human overrides performed')),
            ],
            options={
                'db_table': 'compliance_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
